### ISSUE TITLE
Custom css rule doesnt seem to work

### ISSUE THREAD

**Issue by Parilia** [neoncube2/flarum-private-messages#12]
I have been trying to change the colour of the active username for a converstion, It doesnt seem to change it.

```css
.ConversationsList .people-list .UserListItem.active {
  background-color: #1e99a6;
}
```
